defaults:
  - agent: ppo
  - env: default
  - run: default
  - _self_
  - override hydra/launcher: joblib

tag: ''

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}${tag}

debug: true
