# ppo parameters
learning_rate: 3e-4
#n_steps: 2048
n_steps: 128
#gamma: 0.99
gamma: 0.9
gae_lambda: 1.0
#ent_coef: 0.0
ent_coef: 1e-2
vf_coef: 0.5
#max_grad_norm: 0.5
max_grad_norm: 10_000
use_sde: False
sde_sample_freq: -1
normalize_advantage: False
