# ppo parameters
learning_rate: 3e-4
#gamma: 0.99
gamma: 0.9
gae_lambda: 1.0
ent_coef: 0.0
#ent_coef: 1.0 #- causes reward overflow
vf_coef: 0.5
#max_grad_norm: 0.5
max_grad_norm: 10_000
use_sde: False
sde_sample_freq: -1
normalize_advantage: False
