# time config
train_ep_start: '2016-01-01 00:00:00'
train_ep_end: '2021-01-01 00:00:00'
test_ep_start: ${env.train_ep_end}
test_ep_end: '2022-01-01 00:00:00'
scheduling_time: '10:30:00'
action_time: '00:00:00'

# battery config
bat_cap: 0.1
bat_efficiency: 1.0
bat_init_charge: 0.05

# wallet config
init_balance: 10_000

debug: True
